import marimo

__generated_with = "0.24.2"
app = marimo.App()


@app.cell
def _():
    import marimo as mo

    return (mo,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Getting started with Echopype

    In this notebook, we will focus on the steps to convert instrument-generated raw data files, compute the volume backscattering strength (Sv) based on calibration and environmental parameters already stored in the file, and plot an echogram.
    We will use a `.raw` file generated by a Simrad EK80 echosounder as an example.
    Please see the Echopype [documentation](https://echopype.readthedocs.io/en/stable/convert.html#supported-raw-file-types) for usage with other supported formats.
    """)
    return


@app.cell
def _():
    import warnings
    from pathlib import Path

    import echopype as ep  # we recommend using "ep"
    import xarray as xr
    import hvplot.xarray  # for interactive plots

    import matplotlib.pyplot as plt

    return Path, ep, warnings, xr


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    Here we will use an example file collected as part of the [Hake survey](https://www.fisheries.noaa.gov/west-coast/science-data/joint-us-canada-integrated-ecosystem-and-pacific-hake-acoustic-trawl-survey) run by the NOAA Northwest Fisheries Science Center, stored in an [open AWS data register from NOAA NCEI](https://registry.opendata.aws/ncei-wcsd-archive/).

    Echopype supports accessing data from multiple sources, such as a local filesystem (e.g., hard disk), a cloud object store (e.g., AWS S3), an http server, etc.

    Here we directly access and convert data from an S3 bucket without having to download them first.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Convert raw data
    """)
    return


@app.cell
def _(ep):
    raw_path = "s3://noaa-wcsd-pds/data/raw/Bell_M._Shimada/SH2306/EK80/Hake-D20230811-T165727.raw"
    ed = ep.open_raw(
        raw_path,
        sonar_model="EK80",
        storage_options={"anon": True},  # open bucket, otherwise need credential
    )
    return (ed,)


@app.cell
def _(ed):
    type(ed)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    Let's take a look at what's in `ed`, and `EchoData` object.

    An `EchoData` object is a representation of an echopype-adapted version of the SONAR-netCDF4 version 1 convention. It shows the tree-like group structure in the netCDF data model. We aim for the conversion from raw data to the `EchoData` object as lossless as possible.

    To see what we changed from the convention and why, please see the **Data standardization** section of the [Echopype paper](https://doi.org/10.1093/icesjms/fsae133).
    """)
    return


@app.cell
def _(ed):
    ed
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    There are a few things to note in this example:
    - All backscatter data are in the `Sonar/Beam_group1` group
    - The backscatter data and many other variables are aligned in 3 major dimensions: `channel`, `ping_time`, `range_sample`
        - `channel` includes all the transducer channel, and for EK80 files these are the channel IDs configured in the EK80 system during data collection.
        - We chose to use `channel` instead of frequency to align the data, because some setups use multiple transducers transmitting at the same frequency but pointing in different directions. Additionally, "frequency" can be a misnomer broadband transmissions
        - We store the "frequency" of the channels in the variable `frequency_nominal` for easy access
        - `range_sample` are 0-based sample count of the received echoes
    - Useful overview type of information are stored in the `Top-level` group, which is the "root" of the netCDF file
    - Raw NMEA datagrams are found in the `Platform/NMEA` group
    - Raw CONFIG datagram, which is an XML string, is save in the variable `content` in the `Vendor_specific` group

    In addition, since `ed` is just converted and has not been saved, everything is stored **in-memory**, as indicated in the first line printed out below.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    :::{note}
    Echopype does not yet support ping-sequence files! We expect that to be part of an upcoming releases.
    :::
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ### Saving the `EchoData` object
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    Echopype supports saving the `EchoData` object into a netCDF file (`.nc`) or a zarr store (`.zarr`). The groups and the representation stay the same, just the format specification is different. NetCDF files are single files that are easy to handle on a conventional filesystem. Zarr stores are optimized for cloud storage, but can be messy to access on a local filesystem as it would show up as many many folder. Both formats and the tools to access them continue to develop, and in particular there are recent new packages that allow representing multiple netCDF files as a virtual zarr store, so things are becoming more convenient and powerful on the user side!
    """)
    return


@app.cell
def _(Path):
    export_path = Path.cwd() / "exports/getting_started"
    export_path.mkdir(exist_ok=True, parents=True)
    return (export_path,)


@app.cell
def _(ed, export_path, warnings):
    # Save to a zarr file
    export_file = export_path / "ed_example.zarr"

    # Ignore zarr errors coming from new features that are not yet stable
    from zarr.errors import ZarrUserWarning
    from zarr.core.dtype.common import UnstableSpecificationWarning
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=ZarrUserWarning)
        warnings.filterwarnings("ignore", category=UnstableSpecificationWarning)
        ed.to_zarr(export_file, overwrite="w")
    return (export_file,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ### Lazy-load an `EchoData` object
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    We can load the saved zarr back using the `open_converted` function.

    By using `chunks={}`, we "lazy-load" all the data in this zarr file into a new `EchoData` object, `ed_new`, which can be seen as a representation or a handle of the data stored on disk.

    This capability is very important for distributed computing and is key to out-of-core computation, because different "workers" can directly access different parts of the same file on disk, and don't have load the entire dataset into memory. This file is pretty small, but in the `OOI_eclipse.ipynb` notebook, you can see an example in which the zarr file is approximately 8 GB and its computation would generally overwhelm a regular laptop without distributed computing capability.
    """)
    return


@app.cell
def _(ep, export_file):
    ed_new = ep.open_converted(export_file, chunks={})
    return (ed_new,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    We can find out if a variable is lazy-loaded or completely loaded into memory by looking at the representation:
    """)
    return


@app.cell
def _(ed):
    # In-memory: see all the values
    ed["Sonar/Beam_group1"]["backscatter_r"]
    return


@app.cell
def _(ed_new):
    # Lazy-loaded: see the entire array size and the chunk size
    ed_new["Sonar/Beam_group1"]["backscatter_r"]
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    We just need 1 `EchoData` for processing below, so we can delete `ed_new`.
    """)
    return


@app.cell
def _(ed_new):
    del ed_new
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ### Accessing `EchoData` groups directly via xarray
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    Note that the zarr or netCDF files on disk are actually standard files, and can be access using regular xarray functions. For example, we an access the GPS data stored in the `Platform` group directly using `xarray.open_dataset`:
    """)
    return


@app.cell
def _(export_file, warnings, xr):
    with warnings.catch_warnings():
        warnings.simplefilter(action="ignore", category=RuntimeWarning)  # ignore warning to focus on tutorial message

        ds_platform = xr.open_dataset(f"{export_file}/Platform", engine="zarr")
    return (ds_platform,)


@app.cell
def _(ds_platform):
    ds_platform
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Compute Sv

    We can then proceed to compute Sv from the raw data. Here, we will use the calibration and environmental parameters already stored in the original instrument-generated `.raw` file to do it. Echopype also supports updating these parameters as part of the function call, or use an Echoview `.ECS` file (though note that this functionality is in beta and may not cover all the equivalent vocabulary recognized by Echoview).
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    `compute_Sv` requires two arguments: `waveform_mode` and `encode_mode`, because EK80 files can contain data from a variety of sampling configurations, including:
    - narrowband data stored in power-angle format (`waveform_mode="CW", encode_mode="power"`)
    - narrowband data stored in complex format (`waveform_mode="CW", encode_mode="complex"`)
    - broadband data stored in complex format (`waveform_mode="FM", encode_mode="complex"`)

    For AZFP echosounder, the arguments will always be `waveform_mode="CW", encode_mode="power"` since the instrument does not yet support broadband transmissions.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    **If these arguments are not provided, `compute_Sv` will error out for EK80 data.**
    """)
    return


@app.cell
def _(ed, ep):
    # Use the correct waveform_mode and encode_mode combination
    ds_Sv = ep.calibrate.compute_Sv(ed, waveform_mode="CW", encode_mode="power")
    return (ds_Sv,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ### Content of the Sv dataset
    """)
    return


@app.cell
def _(ds_Sv):
    ds_Sv
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    `ds_Sv` is a standard xarray `Dataset` with multiple data variable, each an xarray `DataArray`.

    In addition to the `Sv` variable, there are many other variables in this dataset, including:
    - all calibration and environmental parameters used to compute the Sv values, to ensure traceability and reproducibility
    - the `echo_range` variable that contains the range of each echo sample from the transducer

    `echo_range` has the same dimension as the `Sv` variable, because the sampling rate of the echo time series (step size along range) and sound speed may vary across pings depending on the echosounder configuration and the environment.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    It is also often useful to have the Sv dataset aligned with the `frequency_nominal` instead of `channel`:
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    Let's take a quick look at what the Sv data looks like:
    """)
    return


@app.cell
def _(ds_Sv):
    ds_Sv["Sv"].plot(
        x="ping_time", 
        row="channel", col_wrap=3,
        vmin=-80, vmax=-30,
        cmap="RdYlBu_r", yincrease=False
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    We can see that there are lots of `NaN` (empty) entries in this dataset, and the number of along-range samples are different for different channels. This is because the echosounder was configured to collect data up to different range, and the sample interval (step size) can also be different for different channels.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    :::{tip}
    In Echopype, we chose to pad `NaN` for shorter pings and channels, so that the data are **gridded** at the raw data and all subsequent stages. This makes it much easier to slice different parts of data out, and helps with computing efficiency.

    This choice is one of the key differences between Echopype-adapted data format and SONAR-netCDF4 definitions. See the Echopype [documentation](https://echopype.readthedocs.io/en/stable/data-format-sonarnetcdf4.html#nan-padding) for more information.
    :::
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ### Correct reversed ping time

    For some reason, the EK echosounders sometimes generate ping times that are reversed in time, by a tiny amount (<1 msec scale). Reversed coordinate values are problematic for xarray and many operations, and we can correct them by using functions in the `qc` subpackage:
    """)
    return


@app.cell
def _(ds_Sv):
    # Correct reveresed ping time
    from echopype.qc import exist_reversed_time, coerce_increasing_time

    if exist_reversed_time(ds_Sv, "ping_time"):
        # Coerce increasing time
        coerce_increasing_time(ds_Sv)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Add additional information to the Sv dataset

    The Sv dataset generated by `compute_Sv` only contains backscatter data, but we often need additional information, such as the latitude/longitutude location of the platform, or the split-beam angle inferred from the echo time series. We can add these into the dataset by calling functions from the `consolidate` subpackage. We can also compute the depth of each echo sample if the platform depth is known.

    For data saved in complex format, the split-beam angles are calculated from the samplesy. For data saved in power-angle format, the split-beam angle is directly extracted from the `EchoData` object since it's already part of the raw file.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    :::{note}
    Echopype does not yet support heave compensation.
    :::
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    Adding depth and split-beam angle would run through fine:
    """)
    return


@app.cell
def _(ds_Sv, ed, ep):
    # Add depth
    # depth_offset=9.8 because transducer was on a lowered centerboard at 9.8 m deep
    ds_Sv_1 = ep.consolidate.add_depth(ds_Sv, ed, depth_offset=9.8)
    return (ds_Sv_1,)


@app.cell
def _(ds_Sv_1, ed, ep):
    # Add split-beam angle
    # also need waveform_mode and encode_mode to determine how to extract or compute split-beam angles
    ds_Sv_2 = ep.consolidate.add_splitbeam_angle(ds_Sv_1, ed, waveform_mode='CW', encode_mode='power', to_disk=False)
    return (ds_Sv_2,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    To add geographical location, we use add_location(). However, this file contains duplicate timestamps in the `time1` coordinate because multiple NMEA sentence types are present. Previously, these duplicates had to be removed manually before calling add_location(). Since echopype PR [#1627](https://github.com/echostack-org/echopype/pull/1627), `add_location()` automatically keeps the first occurrence, issues a warning, and continues interpolating the location data onto the `ping_time` coordinate.
    """)
    return


@app.cell
def _(ds_Sv_2, ed, ep, warnings):
    # We capture the warning message for display
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter('always')
        ds_Sv_3 = ep.consolidate.add_location(ds_Sv_2, ed)
    print(f'{caught[0].category.__name__}: {caught[0].message}')  # Add geographical location
    return (ds_Sv_3,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    After these operations, we now have an Sv dataset that contains pretty useful data that we can use for downstream analysis.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Compute MVBS
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    We can bring them onto the same grid by computing the mean volume backscattering strength (MVBS):
    """)
    return


@app.cell
def _(ds_Sv_3, ep):
    # Compute MVBS
    ds_MVBS = ep.commongrid.compute_MVBS(ds_Sv_3, range_var='depth', range_bin='1m', ping_time_bin='5s', range_var_max='500m')  # max range to bin
    return (ds_MVBS,)


@app.cell
def _(ds_MVBS):
    # It's often useful to display frequency_nominal rather than channel
    ds_MVBS_1 = ds_MVBS.swap_dims({'channel': 'frequency_nominal'})
    return (ds_MVBS_1,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    Now, all channels are bin-averaged on the same grid:
    """)
    return


@app.cell
def _(ds_MVBS_1):
    ds_MVBS_1['Sv'].plot(x='ping_time', row='frequency_nominal', col_wrap=3, cmap='RdYlBu_r', yincrease=False, vmin=-85, vmax=-45)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    And we can use `hvPlot` to quickly plot an interactive figure:
    """)
    return


@app.cell
def _(ds_MVBS_1):
    ds_MVBS_1['Sv'].hvplot.quadmesh(x='ping_time', clim=(-80, -30), figsize=(6, 6), cmap='RdYlBu_r', rasterize=True, groupby='frequency_nominal').opts(invert_yaxis=True, height=400)
    return


if __name__ == "__main__":
    app.run()
